"use client";
import { useState } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import Link from "next/link";

// Optional: basic translation dictionary
const dictionary: Record<string, string> = {
    // Basic vocabulary
    "the": "کی",
    "and": "اور",
    "that": "کہ",
    "have": "ہے",
    "for": "کے لیے",
    "not": "نہیں",
    "with": "کے ساتھ",
    "this": "یہ",
    "they": "وہ",
    "will": "گا",

    // Common verbs
    "be": "ہونا",
    "do": "کرنا",
    "say": "کہنا",
    "get": "حاصل کرنا",
    "make": "بنانا",
    "go": "جانا",
    "see": "دیکھنا",
    "know": "جاننا",
    "take": "لینا",
    "think": "سوچنا",
    "come": "آنا",
    "give": "دینا",
    "look": "دیکھو",
    "use": "استعمال کرنا",
    "find": "تلاش کرنا",
    "tell": "بتانا",
    "ask": "پوچھنا",
    "work": "کام",
    "seem": "لگنا",
    "feel": "محسوس کرنا",
    "try": "کوشش کرنا",
    "leave": "چھوڑنا",
    "call": "بلانا",

    // Common nouns
    "time": "وقت",
    "year": "سال",
    "day": "دن",
    "way": "طریقہ",
    "man": "آدمی",
    "world": "دنیا",
    "life": "زندگی",
    "hand": "ہاتھ",
    "part": "حصہ",
    "child": "بچہ",
    "eye": "آنکھ",
    "woman": "عورت",
    "place": "جگہ",
    "case": "کیس",
    "group": "گروہ",
    "company": "کمپنی",
    "problem": "مسئلہ",
    "fact": "حقیقت",
    "point": "نقطہ",
    "home": "گھر",
    "story": "کہانی",

    // Technology terms
    "technology": "ٹیکنالوجی",
    "internet": "انٹرنیٹ",
    "computer": "کمپیوٹر",
    "phone": "فون",
    "software": "سافٹ ویئر",
    "data": "ڈیٹا",
    "system": "سسٹم",
    "information": "معلومات",
    "network": "نیٹ ورک",
    "digital": "ڈیجیٹل",
    "device": "ڈیوائس",
    "application": "ایپلیکیشن",
    "website": "ویب سائٹ",
    "social": "سوشل",
    "media": "میڈیا",

    // Business/Finance
    "business": "کاروبار",
    "money": "پیسہ",
    "market": "مارکیٹ",
    "price": "قیمت",
    "product": "پروڈکٹ",
    "service": "سروس",
    "customer": "کسٹمر",
    "sale": "سیل",
    "bank": "بینک",
    "investment": "سرمایہ کاری",
    "growth": "ترقی",
    "profit": "منافع",
    "loss": "نقصان",
    "trade": "تجارت",
    "industry": "انڈسٹری",

    // Health/Medical
    "doctor": "ڈاکٹر",
    "hospital": "ہسپتال",
    "patient": "مریض",
    "medicine": "دوا",
    "treatment": "علاج",
    "research": "تحقیق",
    "study": "مطالعہ",
    "test": "ٹیسٹ",
    "result": "نتیجہ",
    "symptom": "علامت",
    "virus": "وائرس",
    "vaccine": "ویکسین",
    "pandemic": "وبا",

    // Education
    "school": "اسکول",
    "student": "طالب علم",
    "teacher": "استاد",
    "class": "کلاس",
    "education": "تعلیم",
    "learning": "سیکھنا",
    "book": "کتاب",
    "university": "یونیورسٹی",
    "exam": "امتحان",
    "knowledge": "علم",
    "skill": "مہارت",

    // Add 100+ more words below...
    "water": "پانی",
    "food": "کھانا",
    "air": "ہوا",
    "fire": "آگ",
    "earth": "زمین",
    "love": "محبت",
    "friend": "دوست",
    "family": "خاندان",
    "city": "شہر",
    "country": "ملک",
    "language": "زبان",
    "culture": "ثقافت",
    "art": "فن",
    "music": "موسیقی",
    "film": "فلم",
    "sport": "کھیل",
    "game": "گیم",
    "news": "خبریں",
    "weather": "موسم",
    "nature": "فطرت",
    "tree": "درخت",
    "flower": "پھول",
    "animal": "جانور",
    "bird": "پرندہ",
    "fish": "مچھلی",
    "color": "رنگ",
    "number": "نمبر",
    "age": "عمر",
    "body": "جسم",
    "heart": "دل",
    "mind": "دماغ",
    "soul": "روح",
    "god": "خدا",
    "religion": "مذہب",
    "politics": "سیاست",
    "law": "قانون",
    "right": "حق",
    "war": "جنگ",
    "peace": "امن",
    "history": "تاریخ",
    "future": "مستقبل",
    "science": "سائنس",
    "space": "خلاء",
    "moon": "چاند",
    "sun": "سورج",
    "star": "ستارہ",
    "light": "روشنی",
    "dark": "اندھیرا",
    "hot": "گرم",
    "cold": "سرد",
    "big": "بڑا",
    "small": "چھوٹا",
    "new": "نیا",
    "old": "پرانا",
    "good": "اچھا",
    "bad": "برا",
    "true": "سچ",
    "false": "جھوٹ",
    "beautiful": "خوبصورت",
    "ugly": "بدصورت",
    "rich": "امیر",
    "poor": "غریب",
    "strong": "مضبوط",
    "weak": "کمزور",
    "happy": "خوش",
    "sad": "اداس",
    "angry": "غصہ",
    "calm": "پرسکون",
    "noise": "شور",
    "quiet": "خاموش",
    "fast": "تیز",
    "slow": "آہستہ",
    "clean": "صاف",
    "dirty": "گندا",
    "full": "بھرا",
    "empty": "خالی",
    "same": "ایک جیسا",
    "different": "مختلف",
    "easy": "آسان",
    "hard": "مشکل",
    "begin": "شروع",
    "end": "ختم",
    "first": "پہلا",
    "last": "آخری",
    "young": "جوان",
    "important": "اہم",
    "interesting": "دلچسپ",
    "boring": "بیزار کن",
    "dangerous": "خطرناک",
    "safe": "محفوظ",
    "free": "آزاد",
    "busy": "مصروف",
    "ready": "تیار",
    "tired": "تھکا ہوا",
    "hungry": "بھوکا",
    "thirsty": "پیاسا",
    "awake": "جاگتا",
    "asleep": "سوتا",
    "alive": "زندہ",
    "dead": "مردہ",
    "present": "موجود",
    "absent": "غائب",
    "correct": "صحیح",
    "wrong": "غلط",
    "open": "کھلا",
    "closed": "بند",
    "public": "عوامی",
    "private": "ذاتی",
    "major": "اہم",
    "minor": "چھوٹا",
    "real": "حقیقی",
    "fake": "جعلی",
    "whole": "پورا",
    "front": "سامنے",
    "back": "پیچھے",
    "left": "بائیں",
    "high": "اونچا",
    "low": "نیچا",
    "near": "قریب",
    "far": "دور",
    "inside": "اندر",
    "outside": "باہر",
    "up": "اوپر",
    "down": "نیچے",
    "early": "جلدی",
    "late": "دیر",
    "always": "ہمیشہ",
    "never": "کبھی نہیں",
    "often": "اکثر",
    "sometimes": "کبھی کبھی",
    "usually": "عام طور پر",
    "very": "بہت",
    "too": "بھی",
    "so": "تو",
    "just": "صرف",
    "now": "اب",
    "then": "پھر",
    "here": "یہاں",
    "there": "وہاں",
    "why": "کیوں",
    "how": "کیسے",
    "what": "کیا",
    "when": "کب",
    "where": "کہاں",
    "who": "کون",
    "which": "کون سا",
    "whose": "کس کا",
    "myself": "میں خود",
    "yourself": "تم خود",
    "himself": "وہ خود",
    "herself": "وہ خود",
    "itself": "یہ خود",
    "ourselves": "ہم خود",
    "yourselves": "تم خود",
    "themselves": "وہ خود",
    "something": "کچھ",
    "anything": "کچھ بھی",
    "nothing": "کچھ نہیں",
    "everything": "سب کچھ",
    "someone": "کوئی",
    "anyone": "کوئی بھی",
    "no one": "کوئی نہیں",
    "everyone": "سب",
    "somewhere": "کہیں",
    "anywhere": "کہیں بھی",
    "nowhere": "کہیں نہیں",
    "everywhere": "ہر جگہ",
    "some": "کچھ",
    "any": "کوئی",
    "no": "نہیں",
    "many": "بہت",
    "few": "کچھ",
    "several": "کئی",
    "all": "سب",
    "both": "دونوں",
    "neither": "نہ ہی",
    "either": "یا تو",
    "each": "ہر ایک",
    "every": "ہر",
    "other": "دوسرا",
    "another": "ایک اور",
    "such": "ایسا",
    "only": "صرف",
    "own": "اپنا",
    "next": "اگلا",
    "previous": "پچھلا",
    "current": "موجودہ",
    "former": "سابق",
    "latter": "آخری",
    "main": "اہم",
    "certain": "یقینی",
    "particular": "خاص",
    "general": "عام",
    "special": "خصوصی",
    "common": "عام",
    "usual": "معمول",
    "normal": "عام",
    "strange": "عجیب",
    "foreign": "غیر ملکی",
    "local": "مقامی",
    "national": "قومی",
    "international": "بین الاقوامی",
    "modern": "جدید",
    "ancient": "قدیم",
    "traditional": "روایتی",
    "cultural": "ثقافتی",
    "political": "سیاسی",
    "economic": "معاشی",
    "military": "فوجی",
    "legal": "قانونی",
    "medical": "طبی",
    "technical": "تکنیکی",
    "scientific": "سائنسی",
    "academic": "تعلیمی",
    "professional": "پیشہ ورانہ",
    "personal": "ذاتی",
    "financial": "مالی",
    "commercial": "تجارتی",
    "industrial": "صنعتی",
    "environmental": "ماحولیاتی",
    "global": "عالمی",
    "regional": "علاقائی",
    "urban": "شہری",
    "rural": "دیہاتی",
    "positive": "مثبت",
    "negative": "منفی",
    "active": "سرگرم",
    "passive": "غیر فعال",
    "direct": "براہ راست",
    "indirect": "بالواسطہ",
    "independent": "آزاد",
    "dependent": "انحصار",
    "similar": "مشابہ",
    "various": "مختلف",
    "multiple": "متعدد",
    "single": "اکیلا",
    "double": "دوگنا",
    "triple": "تین گنا",
    "quarter": "چوتھائی",
    "half": "آدھا",
    "heavy": "بھاری",
    "bright": "روشن",
    "clear": "صاف",
    "cloudy": "بادلوں بھرا",
    "windy": "ہوادار",
    "rainy": "بارش والا",
    "sunny": "دھوپ والا",
    "snowy": "برف باری والا",
    "stormy": "طوفانی",
    "noisy": "شور والا",
    "dry": "خشک",
    "wet": "گیلا",
    "smooth": "ہموار",
    "rough": "کھردرا",
    "soft": "نرم",
    "sharp": "تیز",
    "dull": "کند",
    "neat": "صاف ستھرا",
    "messy": "گندا",
    "tidy": "صاف ستھرا",
    "organized": "منظم",
    "disorganized": "بے ترتیب",
    "simple": "آسان",
    "complex": "پیچیدہ",
    "basic": "بنیادی",
    "advanced": "اعلی",
    "beginner": "نو آموز",
    "expert": "ماہر",
    "amateur": "شوقیہ",
    "official": "سرکاری",
    "unofficial": "غیر سرکاری",
    "formal": "رسمی",
    "informal": "غیر رسمی",
    "secret": "راز",
    "available": "دستیاب",
    "unavailable": "غیر دستیاب",
    "possible": "ممکن",
    "impossible": "ناممکن",
    "likely": "ممکن",
    "unlikely": "ناممکن",
    "uncertain": "غیر یقینی",
    "genuine": "اصلی",
    "artificial": "مصنوعی",
    "natural": "قدرتی",
    "man-made": "انسانی ساختہ",
    "original": "اصل",
    "copy": "نقل",
    "unique": "منفرد",
    "rare": "نایاب",
    "ordinary": "عام",
    "extraordinary": "غیر معمولی",
    "unusual": "غیر معمولی",
    "abnormal": "غیر معمولی",
    "regular": "باقاعدہ",
    "irregular": "بے قاعدہ",
    "frequent": "کثرت سے",
    "infrequent": "کم",
    "constant": "مسلسل",
    "variable": "متغیر",
    "stable": "مستحکم",
    "unstable": "غیر مستحکم",
    "permanent": "مستقل",
    "temporary": "عارضی",
    "complete": "مکمل",
    "incomplete": "نامکمل",
    "finished": "مکمل",
    "unfinished": "نامکمل",
    "successful": "کامیاب",
    "unsuccessful": "ناکام",
    "effective": "موثر",
    "ineffective": "غیر موثر",
    "efficient": "موثر",
    "inefficient": "غیر موثر",
    "productive": "پیداواری",
    "unproductive": "غیر پیداواری",
    "creative": "تخلیقی",
    "destructive": "تباہ کن",
    "constructive": "تعمیری",
    "optimistic": "پر امید",
    "pessimistic": "مایوس",
    "joyful": "خوش",
    "depressed": "اداس",
    "excited": "پرجوش",
    "bored": "بیزار",
    "interested": "دلچسپی رکھنے والا",
    "disinterested": "بے دلچسپی",
    "enthusiastic": "پرجوش",
    "apathetic": "بے حس",
    "passionate": "پر جوش",
    "indifferent": "بے پرواہ",
    "loving": "پیار کرنے والا",
    "hateful": "نفرت کرنے والا",
    "kind": "مہربان",
    "cruel": "ظالم",
    "gentle": "نرم",
    "polite": "شائستہ",
    "rude": "بدتمیز",
    "friendly": "دوستانہ",
    "unfriendly": "غیر دوستانہ",
    "generous": "فیاض",
    "stingy": "کنجوس",
    "honest": "ایماندار",
    "dishonest": "بے ایمان",
    "trustworthy": "قابل اعتماد",
    "untrustworthy": "ناقابل اعتماد",
    "reliable": "قابل اعتماد",
    "unreliable": "ناقابل اعتماد",
    "responsible": "ذمہ دار",
    "irresponsible": "غیر ذمہ دار",
    "mature": "بالغ",
    "immature": "نابالغ",
    "wise": "عقلمند",
    "foolish": "احمق",
    "intelligent": "ذہین",
    "stupid": "بیوقوف",
    "smart": "ہوشیار",
    "dumb": "گونگا",
    "clever": "چالاک",
    "naive": "بھولا",
    "experienced": "تجربہ کار",
    "inexperienced": "بے تجربہ",
    "skilled": "ماہر",
    "unskilled": "نا ماہر",
    "talented": "قابل",
    "untalented": "نا قابل",
    "gifted": "قابل",
    "average": "عام",
    "exceptional": "غیر معمولی",
    "healthy": "صحت مند",
    "unhealthy": "غیر صحت مند",
    "fit": "فٹ",
    "unfit": "غیر فٹ",
    "powerful": "طاقتور",
    "powerless": "بے بس",
    "wealthy": "امیر",
    "penniless": "مفلس",
    "famous": "مشہور",
    "unknown": "نامعلوم",
    "popular": "مقبول",
    "unpopular": "غیر مقبول",
    "unimportant": "غیر اہم",
    "significant": "اہم",
    "insignificant": "غیر اہم",
    "primary": "بنیادی",
    "secondary": "ثانوی",
    "subsidiary": "ذیلی",
    "central": "مرکزی",
    "peripheral": "طرفی",
    "internal": "اندرونی",
    "external": "بیرونی",
    "inner": "اندرونی",
    "outer": "بیرونی",
    "upper": "اوپر والا",
    "lower": "نیچے والا",
    "higher": "اونچا",
    "top": "اوپر",
    "bottom": "نیچے",
    "side": "طرف",
    "middle": "درمیان",
    "center": "مرکز",
    "edge": "کنارہ",
    "corner": "کونا",
    "beginning": "شروع",
    "start": "شروع",
    "finish": "ختم",
    "continue": "جاری رکھیں",
    "stop": "روکیں",
    "pause": "توقف",
    "delay": "تاخیر",
    "hurry": "جلدی کریں",
    "speed": "رفتار",
    "quick": "تیز",
    "rapid": "تیز",
    "sudden": "اچانک",
    "gradual": "آہستہ آہستہ",
    "steady": "مستحکم",
    "unsteady": "غیر مستحکم",
    "even": "ہموار",
    "uneven": "ناہموار",
    "flat": "ہموار",
    "bumpy": "ناہموار",
    "straight": "سیدھا",
    "curved": "مڑا ہوا",
    "bent": "جھکا ہوا",
    "twisted": "مڑا ہوا",
    "round": "گول",
    "square": "مربع",
    "triangular": "مثلثی",
    "rectangular": "مستطیل",
    "circular": "دائرہ نما",
    "oval": "بیضوی",
    "spherical": "کروی",
    "cylindrical": "بیلن نما",
    "conical": "مخروطی",
    "pyramidal": "ہرم نما",
    "cubical": "مکعبی",
    "hexagonal": "شش پہلو",
    "octagonal": "آٹھ پہلو",
    "symmetrical": "متناسب",
    "asymmetrical": "غیر متناسب",
    "balanced": "متوازن",
    "unbalanced": "غیر متوازن",
    "equal": "برابر",
    "unequal": "غیر برابر",
    "identical": "ایک جیسا",
    "dissimilar": "غیر مشابہ",
    "alike": "ایک جیسا",
    "unlike": "مختلف",
    "opposite": "مخالف",
    "contrary": "الٹ",
    "reverse": "الٹ",
    "inverse": "الٹ",
    "complementary": "تکمیلی",
    "supplementary": "اضافی",
    "additional": "اضافی",
    "extra": "اضافی",
    "spare": "فالتو",
    "leftover": "بچا ہوا",
    "remaining": "باقی",
    "excess": "اضافی",
    "surplus": "فاضل",
    "deficit": "کمی",
    "shortage": "کمی",
    "lack": "کمی",
    "abundance": "کثرت",
    "plenty": "کافی",
    "sufficient": "کافی",
    "insufficient": "ناکافی",
    "adequate": "کافی",
    "inadequate": "ناکافی",
    "enough": "کافی",
    "more": "مزید",
    "less": "کم",
    "most": "سب سے زیادہ",
    "least": "سب سے کم",
    "numerous": "بہت",
    "countless": "ان گنت",
    "infinite": "لامحدود",
    "finite": "محدود",
    "limited": "محدود",
    "unlimited": "لامحدود",
    "restricted": "محدود",
    "unrestricted": "غیر محدود",
    "bound": "محدود",
    "confined": "محدود",
    "locked": "تالا لگا",
    "unlocked": "کھلا",
    "secure": "محفوظ",
    "insecure": "غیر محفوظ",
    "risky": "خطرناک",
    "hazardous": "خطرناک",
    "harmful": "نقصان دہ",
    "harmless": "بے ضرر",
    "toxic": "زہریلا",
    "poisonous": "زہریلا",
    "deadly": "مہلک",
    "fatal": "مہلک",
    "lethal": "مہلک",
    "non-toxic": "غیر زہریلا",
    "edible": "کھانے کے قابل",
    "inedible": "ناقابل تناول",
    "digestible": "ہضم ہونے والا",
    "indigestible": "ناقابل ہضم",
    "nutritious": "غذائیت بخش",
    "non-nutritious": "غیر غذائیت بخش",
    "wholesome": "صحت بخش",
    "unwholesome": "غیر صحت بخش",
    "fresh": "تازہ",
    "stale": "باسی",
    "rotten": "سڑا ہوا",
    "spoiled": "خراب",
    "contaminated": "آلودہ",
    "polluted": "آلودہ",
    "pure": "خالص",
    "impure": "نا خالص",
    "sterile": "جراثیم سے پاک",
    "unsterile": "جراثیم سے آلودہ",
    "sanitary": "صاف ستھرا",
    "unsanitary": "گندا",
    "hygienic": "صاف ستھرا",
    "unhygienic": "گندا",
    "untidy": "گندا",
    "orderly": "منظم",
    "chaotic": "افراتفری",
    "systematic": "منظم",
    "unsystematic": "بے ترتیب",
    "methodical": "منظم",
    "random": "بے ترتیب",
    "planned": "منصوبہ بند",
    "unplanned": "بے منصوبہ",
    "intentional": "ارادی",
    "accidental": "حادثاتی",
    "deliberate": "جان بوجھ کر",
    "inadvertent": "غیر ارادی",
    "conscious": "ہوش میں",
    "unconscious": "بے ہوش",
    "aware": "آگاہ",
    "unaware": "بے خبر",
    "knowledgeable": "جانکار",
    "ignorant": "جاہل",
    "educated": "تعلیم یافتہ",
    "uneducated": "ان پڑھ",
    "literate": "پڑھا لکھا",
    "illiterate": "ان پڑھ",
    "trained": "تربیت یافتہ",
    "untrained": "بے تربیت",
    "qualified": "قابل",
    "unqualified": "نا قابل",
    "veteran": "تجربہ کار",
    "master": "ماہر",
    "apprentice": "شاگرد",
    "instructor": "استاد",
    "learner": "سیکھنے والا",
    "trainer": "ٹرینر",
    "trainee": "ٹرینی",
    "coach": "کوچ",
    "player": "کھلاڑی",
    "captain": "کپتان",
    "leader": "رہنما",
    "follower": "پیروکار",
    "boss": "مالک",
    "employee": "ملازم",
    "manager": "مینیجر",
    "worker": "کارکن",
    "laborer": "مزدور",
    "supervisor": "نگران",
    "subordinate": "ماتحت",
    "colleague": "ساتھی",
    "partner": "شریک",
    "assistant": "معاون",
    "helper": "مددگار",
    "volunteer": "رضاکار",
    "donor": "عطیہ دہندہ",
    "recipient": "وصول کنندہ",
    "giver": "دینے والا",
    "receiver": "لینے والا",
    "buyer": "خریدار",
    "seller": "فروخت کنندہ",
    "client": "کلائنٹ",
    "consumer": "صارف",
    "producer": "پیدا کرنے والا",
    "manufacturer": "صنعت کار",
    "distributor": "تقسیم کار",
    "retailer": "خوردہ فروش",
    "wholesaler": "تھوک فروش",
    "supplier": "فراہم کنندہ",
    "vendor": "فروخت کنندہ",
    "merchant": "تاجر",
    "trader": "تاجر",
    "dealer": "ڈیلر",
    "broker": "دلال",
    "agent": "ایجنٹ",
    "representative": "نمائندہ",
    "ambassador": "سفیر",
    "diplomat": "سفارت کار",
    "politician": "سیاستدان",
    "statesman": "سیاستدان",
    "ruler": "حاکم",
    "governor": "گورنر",
    "mayor": "میئر",
    "president": "صدر",
    "prime minister": "وزیر اعظم",
    "minister": "وزیر",
    "secretary": "سیکرٹری",
    "officer": "افسر",
    "civil servant": "سرکاری ملازم",
    "public servant": "عوامی خدمت گزار",
    "specialist": "ماہر",
    "consultant": "مشیر",
    "advisor": "مشیر",
    "counselor": "مشیر",
    "therapist": "تھراپسٹ",
    "physician": "طبیب",
    "surgeon": "سرجن",
    "nurse": "نرس",
    "dentist": "دانتوں کا ڈاکٹر",
    "pharmacist": "دواساز",
    "veterinarian": "جانوروں کا ڈاکٹر",
    "psychologist": "نفسیات دان",
    "psychiatrist": "نفسیاتی معالج",
    "scientist": "سائنسدان",
    "researcher": "محقق",    
    };

export default function ViewBlogPage() {
  const [url, setUrl] = useState("");
  const [blogContent, setBlogContent] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [showUrdu, setShowUrdu] = useState(false);

  const translateToUrdu = (text: string): string => {
    return text
      .split(" ")
      .map((word) => dictionary[word.toLowerCase()] || word)
      .join(" ");
  };

  const handleViewBlog = async () => {
    setLoading(true);
    setError("");
    setBlogContent(null);

    try {
      const response = await fetch("/api/scrap", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url }),
      });

      const data = await response.json();

      if (!response.ok || !data.content) {
        throw new Error(data.error || "Something went wrong.");
      }

      setBlogContent(data.content);
    } catch (err: any) {
      setError(err.message || "Failed to fetch blog content.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="relative min-h-screen flex flex-col items-center justify-center gap-8 p-4">
      {/* Blurred Background */}
      <div
        className="absolute inset-0 bg-[url('/background.jpg')] bg-cover filter blur-[2px] opacity-30 z-0"
        aria-hidden="true"
      />

      {/* Input Card */}
      <div className="relative z-10 w-full max-w-md space-y-4 shadow-lg p-6 rounded-lg bg-white/90 backdrop-blur">
        <h1 className="text-4xl font-bold text-center">View a Blog</h1>

        <Input
          placeholder="Enter blog URL..."
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          className="shadow-inner"
        />
        <Button
          onClick={handleViewBlog}
          className="w-full shadow-md"
          disabled={loading}
        >
          {loading ? "Loading..." : "View Blog"}
        </Button>

        {error && <p className="text-red-500 text-sm">{error}</p>}
      </div>

      {/* Blog Display */}
      {blogContent && (
        <div className="relative z-10 max-w-2xl p-6 mt-6 bg-white/90 shadow-md rounded-lg border backdrop-blur transform transition duration-300 hover:scale-105 hover:shadow-lg">
          {/* Urdu Toggle */}
          <div className="absolute top-4 right-4 flex items-center gap-2">
            <label className="text-sm text-gray-600">Urdu</label>
            <Switch checked={showUrdu} onCheckedChange={setShowUrdu} />
          </div>

          <h2 className="text-xl font-semibold mb-4 text-center">Blog Content:</h2>
          <p className="text-gray-800 whitespace-pre-line leading-relaxed">
            {showUrdu ? translateToUrdu(blogContent) : blogContent}
          </p>
        </div>
      )}

      <Link href="/">
        <Button variant="ghost" className="relative z-10 shadow-sm bg-white/100">
          ← Back to Home
        </Button>
      </Link>
    </div>
  );
}
